### Variables
@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OWM1NWE0ZDNhZjY4M2U2MDBiOGMzYjIiLCJlbWFpbCI6ImFkbWluQG9tcy5jb20iLCJyb2xlIjoiYWRtaW4iLCJtZXJjaGFudElkIjoiNjljNTVhNGQzYWY2ODNlNjAwYjhjM2IyIiwiaWF0IjoxNzc0NTQxNTA2LCJleHAiOjE3NzQ2Mjc5MDZ9.y5D_9HhAYoS0dtTdU84pPYfamsz7qiKRpxkDKPgNmVg
@merchantId = 69c562ccc3e90ec52417eb6e
@workflowId = 69c5653076b1c1acb368cc7f
@orderId = 69c50e3a1f21c990fb0b87d1

###########################################################
### ETAPE 1 — AUTH
###########################################################

### 1. Inscription Admin
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "admin@oms.com",
  "name": "Admin",
  "password": "password123",
  "role": "admin"
}

###

### 2. Login Admin → copier userId dans @merchantId et accessToken dans @token
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@oms.com",
  "password": "password123"
}

###########################################################
### ETAPE 2 — CRÉER LE WORKFLOW (connecté en tant qu'admin)
###########################################################

### 3. Créer le workflow trigger user.registered
POST {{baseUrl}}/workflows
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Réaction inscription",
  "trigger": "user.registered"
}

###

### 4. Ajouter action notify_admin → copier workflowId dans @workflowId
POST {{baseUrl}}/workflows/{{workflowId}}/actions
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "type": "notify_admin",
  "order": 1
}

###

### 5. Ajouter action create_log
POST {{baseUrl}}/workflows/{{workflowId}}/actions
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "type": "create_log",
  "order": 2
}

###########################################################
### ETAPE 3 — INSCRIRE UN MERCHANT (déclenche user.registered)
###########################################################

### 6. Inscription Merchant - déclenche automatiquement le workflow
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "merchant@oms.com",
  "name": "John Doe22",
  "password": "password123",
  "role": "merchant"
}

###########################################################
### ETAPE 4 — VÉRIFIER L'EXÉCUTION DU WORKFLOW
###########################################################

### 7. Voir les exécutions → doit afficher status: success, logs: [notify_admin: OK, create_log: OK]
GET {{baseUrl}}/workflows/{{workflowId}}/executions
Authorization: Bearer {{token}}

###########################################################
### ETAPE 5 — TESTER order.created
###########################################################

### 8. Login Merchant → copier accessToken dans @token
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "merchant@oms.com",
  "password": "password123"
}

###

### 9. Créer un workflow trigger order.created (condition: total > 100)
POST {{baseUrl}}/workflows
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Réaction création commande",
  "trigger": "order.created",
  "condition": {
    "field": "total",
    "operator": "<",
    "value": 100
  }
}

###

### 9b. Créer une commande qui passe  la condition (total = 19.99)
POST {{baseUrl}}/orders
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "customerEmail": "customer@test.com",
  "items": [
    {
      "productId": "prod-cheap",
      "quantity": 1,
      "price": 19.99
    }
  ]
}

###

### 10. Ajouter action notify_user
POST {{baseUrl}}/workflows/{{workflowId}}/actions
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "type": "notify_user",
  "order": 1
}

###

### 11. Ajouter action create_log
POST {{baseUrl}}/workflows/{{workflowId}}/actions
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "type": "create_log",
  "order": 2
}

###

### 12. Créer une commande → déclenche order.created
### Créer une commande qui NE passe PAS la condition (total = 119.97)
POST {{baseUrl}}/orders
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "customerEmail": "customer@test.com",
  "items": [
    {
      "productId": "prod-001",
      "quantity": 2,
      "price": 49.99
    },
    {
      "productId": "prod-002",
      "quantity": 1,
      "price": 19.99
    }
  ]
}

###

### 13. Voir les exécutions → doit afficher status: success
GET {{baseUrl}}/workflows/{{workflowId}}/executions
Authorization: Bearer {{token}}

###

### 14. Lister tous mes workflows
GET {{baseUrl}}/workflows
Authorization: Bearer {{token}}

###

### 15. Activer / Désactiver un workflow (toggle)
PATCH {{baseUrl}}/workflows/{{workflowId}}/toggle
Authorization: Bearer {{token}}
###

### 15. changement de status (order status)
POST {{baseUrl}}/orders/{{orderId}}/status
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "status": "SHIPPED"
}
###

### 16. changement de status (order status) PAID
POST {{baseUrl}}/orders/{{orderId}}/status
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "status": "PAID"
}

###

### 17. Créer un workflow trigger updated.status
POST {{baseUrl}}/workflows
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "reaction changement de status",
  "trigger": "updated.status"
}

###

### 18. Ajouter action notify_user
POST {{baseUrl}}/workflows/{{workflowId}}/actions
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "type": "notify_user",
  "order": 1
}

###

### 19. Ajouter action create_log
POST {{baseUrl}}/workflows/{{workflowId}}/actions
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "type": "create_log",
  "order": 2
}

###

### 12. Créer une commande → déclenche order.created
POST {{baseUrl}}/orders
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "merchantId": "{{merchantId}}",
  "customerEmail": "customer@test.com",
  "items": [
    {
      "productId": "prod-001",
      "quantity": 2,
      "price": 49.99
    },
    {
      "productId": "prod-002",
      "quantity": 1,
      "price": 19.99
    }
  ]
}

###########################################################
### ETAPE 6 — TESTER MANUAL TRIGGER
###########################################################

### 20. Créer un workflow manual.trigger
POST {{baseUrl}}/workflows
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Workflow manuel",
  "trigger": "manual.trigger"
}

###

### 21. Ajouter action create_task → copier workflowId dans @workflowId
POST {{baseUrl}}/workflows/{{workflowId}}/actions
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "type": "create_task",
  "order": 1
}

###

### 22. Déclencher manuellement le workflow
POST {{baseUrl}}/workflows/{{workflowId}}/trigger
Authorization: Bearer {{token}}

###

### 23. Voir les exécutions → doit afficher status: success, logs: [create_task: OK]
GET {{baseUrl}}/workflows/{{workflowId}}/executions
Authorization: Bearer {{token}}

###

### 24. Lister les tâches créées en base
GET {{baseUrl}}/tasks
Authorization: Bearer {{token}}
